spring.application.name=discografia
spring.mongodb.uri=mongodb+srv://estebanhernandezh_db_user:AEY01IBPKveERByx@eva-u3-express.ifwxn4l.mongodb.net/?appName=eva-u3-express
spring.mongodb.database=discografica-db
